#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

// Generic Binary-to-C converter
// Usage: ./font2psf <input_file> <output_file> <array_name>

int main(int argc, char *argv[]) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <input_file> <output_file> <array_name>\n", argv[0]);
        return 1;
    }

    const char *input_path = argv[1];
    const char *output_path = argv[2];
    const char *array_name = argv[3];

    FILE *in = fopen(input_path, "rb");
    if (!in) {
        perror("Error opening input file");
        return 1;
    }

    FILE *out = fopen(output_path, "w");
    if (!out) {
        perror("Error opening output file");
        fclose(in);
        return 1;
    }

    fprintf(out, "// Auto-generated by tools/font2psf\n");
    fprintf(out, "#include <kernel/types.h>\n\n");
    fprintf(out, "__attribute__((aligned(16)))\n");
    fprintf(out, "const uint8_t %s[] = {\n", array_name);

    unsigned char buffer[16];
    size_t bytes_read;
    size_t total_bytes = 0;

    while ((bytes_read = fread(buffer, 1, sizeof(buffer), in)) > 0) {
        fprintf(out, "    ");
        for (size_t i = 0; i < bytes_read; i++) {
            fprintf(out, "0x%02X, ", buffer[i]);
        }
        fprintf(out, "\n");
        total_bytes += bytes_read;
    }

    fprintf(out, "};\n\n");
    fprintf(out, "const uint32_t %s_size = sizeof(%s);\n", array_name, array_name);

    fclose(in);
    fclose(out);

    printf("Successfully embedded %lu bytes from '%s' into '%s' as '%s'.\n", 
           total_bytes, input_path, output_path, array_name);

    return 0;
}