# Generate a C header from a binary file
file(READ ${INPUT_FILE} HEX_DATA HEX)

# Format the hex data as a C array
string(REGEX MATCHALL ".." HEX_LIST ${HEX_DATA})
set(C_ARRAY "")
set(COUNTER 0)
foreach(HEX_BYTE ${HEX_LIST})
    string(APPEND C_ARRAY "0x${HEX_BYTE}, ")
    math(EXPR COUNTER "${COUNTER} + 1")
    math(EXPR MOD_VAL "${COUNTER} % 12")
    if(MOD_VAL EQUAL 0)
        string(APPEND C_ARRAY "\n    ")
    endif()
endforeach()

file(WRITE ${OUTPUT_FILE} "/* Automatically generated by CMake */\n")
file(APPEND ${OUTPUT_FILE} "#pragma once\n\n")
file(APPEND ${OUTPUT_FILE} "static const uint8_t g_fkx_root_key[] = {\n    ${C_ARRAY}\n};\n")
file(APPEND ${OUTPUT_FILE} "#define FKX_KEY_SIZE ${COUNTER}\n")
